fix browser-profile-sync

diff --git a/i3/bin/browser-profile-sync b/i3/bin/browser-profile-sync
--- a/i3/bin/browser-profile-sync
+++ b/i3/bin/browser-profile-sync
@@ -13,6 +13,11 @@ notify() {
   notify-send "${1}" -u ${2}
 }
 
+die() {
+  notify "${1}" critical
+  exit 1
+}
+
 resume() {
   rm ${PRM_DIR}
   mv ${BCK_DIR} ${PRM_DIR}
@@ -20,25 +25,25 @@ resume() {
 
 start() {
   # If tmp directory already exist, profile sync has already been started.
-  if [ -e ${TMP_DIR} ]; then notify "Browser profile sync already started"; exit 1; fi
+  if [ -e ${TMP_DIR} ]; then notify "Browser profile sync already started" normal; exit 1; fi
   # If permanent directory is a symbolic link, then profile sync wasn't cleanly stopped.
-  if [ -L ${PRM_DIR} ]; then notify "Browser profile sync not cleanly stopped. Resuming..."; resume; fi
+  if [ -L ${PRM_DIR} ]; then notify "Browser profile sync not cleanly stopped. Resuming..." normal; resume; fi
   # Copy to tmp directory
-  cp -a ${PRM_DIR} ${TMP_DIR}
+  cp -a ${PRM_DIR} ${TMP_DIR} || die "Cannot start browser profile sync"
   # Permanent directory is the backup directory.
-  mv ${PRM_DIR} ${BCK_DIR}
+  mv ${PRM_DIR} ${BCK_DIR} || die "Cannot start browser profile sync"
   # Let google find the tmp directory
-  ln -s ${TMP_DIR} ${PRM_DIR}
+  ln -s ${TMP_DIR} ${PRM_DIR} || die "Cannot start browser profile sync"
   notify "Browser sync started" low
 }
 
 stop() {
   # If tmp directory does not exist, then profile sync has not started.
-  if [ ! -e ${TMP_DIR} ]; then notify "Browser profile sync not started"; exit 1; fi
+  if [ ! -e ${TMP_DIR} ]; then notify "Browser profile sync not started" normal; exit 1; fi
   # Remove the link.
   rm ${PRM_DIR}
   # Move tmp dir to permanent dir.
-  mv ${TMP_DIR} ${PRM_DIR}
+  mv ${TMP_DIR} ${PRM_DIR} || die "Cannot stop browser profile sync"
   # Backup is not needed, just delete it.
   rm -r ${BCK_DIR}
   notify "Browser sync stopped" low
